# Note that this file should be named jobs.yaml and inside the directory in
# which the results should be saved.

value_function_signature: "sva.value:default_asymmetric_value_function"
value_function_kwargs:
  sd: null
  multiplier: 1.0

truth_function_signature: "sva.truth.sine2phase:truth_sine2phase"

how: "random"

data_kwargs:
  points_per_dimension: 3
  n_raster: null

experiment_fixed_kwargs:
  kernel_signature: "gpytorch.kernels:MaternKernel"
  kernel_kwargs:
    nu: 2.5
  optimize_acqf_kwargs:
    q: 1
    num_restarts: 5
    raw_samples: 20

experiment_run_kwargs:
  n_multiprocessing_jobs: 4
  pbar: True
  max_n_dat: 20
  points_per_dimension_full_grid: 100
  record_gp_every: 2

jobs:
  - acqf_signature: "botorch.acquisition:ExpectedImprovement"
  - acqf_signature: "botorch.acquisition:UpperConfidenceBound"
    acqf_kwargs:
      beta: 1
  - acqf_signature: "botorch.acquisition:UpperConfidenceBound"
    acqf_kwargs:
      beta: 10
  - acqf_signature: "botorch.acquisition:UpperConfidenceBound"
    acqf_kwargs:
      beta: 20
  - acqf_signature: "botorch.acquisition:UpperConfidenceBound"
    acqf_kwargs:
      beta: 100

seed: 123
total_jobs: 2
