[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs/source/conf.py
)/
'''

dependencies = [
    "dunamai",
    "numpy",
    "pandas",
    "scipy",
    "sklearn",
    "tqdm",
    "monty",
    "torch",
    "gpytorch==1.9.0",
    "botorch==0.7.2",
    "loguru"
]

[project.optional-dependencies]
test = [
    "codecov",
    "coverage",
    "flake8",
    "pytest",
    "pytest-cov",
    "black",
    "nbstripout",
    "pre-commit",
]
