_target_: sva.policy.FixedPolicy

acquisition_function:
  _target_: botorch.acquisition.analytic.ExpectedImprovement
  _partial_: true

defaults:
  - _self_
  - common.yaml
  - /models@model_factory: single_task_gp.yaml
