_target_: sva.campaign.FixedSVAPolicy

acquisition_function:
  _target_: botorch.acquisition.analytic.UpperConfidenceBound
  _partial_: true
  beta: 20.0

svf:
  _target_: sva.value.SVF
  params:
    sd: null
    multiplier: 1.0
    characteristic_length: min
    density: false
    symmetric: false

penalty_function_factory: null

defaults:
  - _self_
  - common.yaml
  - /models@model_factory: single_task_gp.yaml


# This provides a good example of how to "inherit" from sva.yaml, though
# it's no longer used in the code:

# penalty_function:
#   _target_: sva.bayesian_optimization.ProximityPenalty
#   _partial_: true
#   divisor: 2.0
#
# penalty_strength: 1.0
#
# defaults:
#   - sva.yaml
#   - _self_
#   - /models@model_factory: single_task_gp.yaml
