_target_: sva.policy.FixedSVAPolicy

acquisition_function:
  _target_: botorch.acquisition.analytic.UpperConfidenceBound
  _partial_: true
  beta: 20.0

svf:
  _target_: sva.value.SVF
  sd: null
  multiplier: 1.0

penalty_function: null

defaults:
  - _self_
  - common.yaml
  - /models@model_factory: single_task_gp.yaml
