defaults:
  - _self_
  - experiment: ???
  - policy: sva.yaml
  - paths: default.yaml
  - data: default.yaml
  - hydra: default.yaml

# name of the runs
name: testing

# Seed for random number generators in pytorch, numpy and python.random
# this seed applies to everything and is propogated through other experiments
# such as in policy performance tuning
seed: 123

# Sets the logging mode
logging: no_console
