defaults:
  - _self_
  - experiment: ???
  - policy: fixed.yaml
  - paths: default.yaml
  - hydra: default.yaml

# name of the runs
name: misc

# Seed for random number generators in pytorch, numpy and python.random
# this seed applies to everything and is propogated through other experiments
# such as in policy performance tuning
seed: 123

# Debugging mode
debug: false

# the number of replications over randomly initializing the experiment
# starting points
replicas: 10

# the number of parallel jobs to run
n_jobs: 12

