likelihood:
  _target_: gpytorch.likelihoods.GaussianLikelihood
mean_module:
  _target_: gpytorch.means.ConstantMean
covar_module:
  _target_: gpytorch.kernels.ScaleKernel
  base_kernel:
    _target_: gpytorch.kernels.MaternKernel
transform_input: true
transform_output: true
