_target_: sva.models.EasySingleTaskGP.from_default
_partial_: true
covar_module:
  _target_: gpytorch.kernels.ScaleKernel
  base_kernel:
    _target_: gpytorch.kernels.MaternKernel
  outputscale_prior:
    _target_: gpytorch.priors.GammaPrior
    concentration: 2.0
    rate: 100.0
defaults:
  - _self_
  - common.yaml
