name: CI-deploy

on:
  push:
    tags:
      - 'v*'

jobs:

  style_syntax:
    uses: ./.github/workflows/style_syntax.yaml

  notebook:
    uses: ./.github/workflows/notebook_smoke.yaml

  unit_tests:
    uses: ./.github/workflows/unit_tests.yaml

  build_and_publish:
    # This workflow follows the best practices outlined here:
    # https://github.com/marketplace/actions/pypi-publish
    # for deploying a project to PyPI via a GH action. It only runs on tags

    name: Upload release to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    needs:
      - style_syntax
      - notebook
      - unit_tests

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/sva

    permissions:
      id-token: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and apply version
      run: bash scripts/build.sh

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
