name: test

on:

  pull_request:
    branches: ["master", "dev/*", "v*"]

  push:
    branches: ["master"]

jobs: 

  style_syntax:
    uses: ./.github/workflows/style_syntax.yaml

  notebooks:
    uses: ./.github/workflows/notebook_smoke.yaml
